apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: churn-model
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: s3://mlops-bucket-975049902478-ap-south-1-an/models/churn_model.pkl